#!/usr/bin/env node

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");
const generatedDir = path.join(repoRoot, "cv", "generated");

function escapeLatex(value) {
  return String(value)
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/([&%$#_{}])/g, "\\$1")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}")
    .replace(/\u2019/g, "'");
}

function parseDate(value) {
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? null : date;
}

function monthLabel(date) {
  const month = String(date.getMonth() + 1).padStart(2, "0");
  return `${date.getFullYear()} / ${month}`;
}

function extractYearFromUrl(url) {
  const match = String(url).match(/(20\d{2})/);
  return match ? match[1] : null;
}

function normalizeTitle(value) {
  return String(value)
    .replace(/\s+/g, " ")
    .replace(/\s+([,.;:!?])/g, "$1")
    .trim();
}

function writeTex(fileName, lines) {
  const content = [
    "% ----------------------------------------------------------------",
    "% THIS FILE IS AUTO-GENERATED BY scripts/sync-cv.mjs.",
    "% DO NOT EDIT MANUALLY.",
    "% ----------------------------------------------------------------",
    "",
    ...lines,
    "",
  ].join("\n");

  return fs.writeFile(path.join(generatedDir, fileName), content, "utf8");
}

function renderProfileSections(profile, publications) {
  const lines = [];
  const { identity, cvHeader, academicAppointments, education, researchInterests, awards } = profile;

  lines.push("%----------------------------------------------------------------------------------------");
  lines.push("%\tCONTACT AND GENERAL INFORMATION");
  lines.push("%----------------------------------------------------------------------------------------");
  lines.push("");
  lines.push(`{\\LARGE\\bfseries ${identity.displayName}}`);
  lines.push("\\bigskip\\bigskip");
  lines.push("");
  lines.push(`${escapeLatex(cvHeader.position)} \\hfill ${escapeLatex(cvHeader.addressLine1)} \\\\`);
  lines.push(`${escapeLatex(cvHeader.institution)} \\hfill ${escapeLatex(cvHeader.addressLine2)} \\\\`);
  lines.push(escapeLatex(cvHeader.organization));
  lines.push("");
  lines.push("\\medskip");
  lines.push("");

  const emails = cvHeader.emails
    .map((email) => `\\href{mailto:${email}}{${escapeLatex(email)}}`)
    .join(" / ");
  const siteUrl = identity.siteUrl.endsWith("/") ? identity.siteUrl : `${identity.siteUrl}/`;
  lines.push(`${emails}~~\\raisebox{0pt}{\\footnotesize\\textbullet}~~ Site: \\href{${siteUrl}}{${escapeLatex(cvHeader.siteLabel)}}`);
  lines.push("");
  lines.push("\\bigskip");
  lines.push("");

  lines.push("%------------------------------------------------");
  lines.push("");
  lines.push("%----------------------------------------------------------------------------------------");
  lines.push("%\tWORK EXPERIENCE");
  lines.push("%----------------------------------------------------------------------------------------");
  lines.push("");
  lines.push("\\section*{Academic Appointment}");
  lines.push("");

  academicAppointments.forEach((appointment, index) => {
    lines.push(`\\years{${escapeLatex(appointment.time)}}\\textbf{${escapeLatex(appointment.institution)}} \\hfill`);
    lines.push(`${escapeLatex(appointment.location)} \\\\`);
    lines.push(escapeLatex(appointment.role));
    if (index !== academicAppointments.length - 1) {
      lines.push("");
      lines.push("\\medskip");
      lines.push("");
    }
  });

  lines.push("");
  lines.push("%----------------------------------------------------------------------------------------");
  lines.push("%\tEDUCATION");
  lines.push("%----------------------------------------------------------------------------------------");
  lines.push("");
  lines.push("\\section*{Education}");
  lines.push("");

  education.forEach((entry, index) => {
    lines.push(`\\years{${escapeLatex(entry.time)}} \\textbf{${escapeLatex(entry.cvInstitution)}} \\hfill ${escapeLatex(entry.cvLocation)} \\\\`);
    lines.push(`${escapeLatex(entry.cvDegree)} \\\\`);

    if (entry.cvDissertation) {
      lines.push(`\\ind Dissertation: \\textit{${escapeLatex(entry.cvDissertation)}} \\\\`);
    }

    if (entry.cvHighlights?.length) {
      entry.cvHighlights.forEach((highlight) => {
        lines.push(`\\ind \\ind \\award{${escapeLatex(highlight)}}\\\\`);
      });
    }

    if (index !== education.length - 1) {
      lines.push("");
    }
  });

  lines.push("");
  lines.push("\\section*{Research Interests}");
  lines.push(`\\years{Topics} ${escapeLatex(researchInterests.topics)}\\\\`);
  lines.push(`\\years{Method} ${escapeLatex(researchInterests.methods)}`);
  lines.push("");
  lines.push("");
  lines.push("%----------------------------------------------------------------------------------------");
  lines.push("%\tGRANTS, HONOURS AND AWARDS");
  lines.push("%----------------------------------------------------------------------------------------");
  lines.push("");
  lines.push("\\section*{Awards}");

  awards.forEach((award) => {
    const titleWithOptionalDescription = award.description
      ? `${award.title} (${award.description})`
      : award.title;

    lines.push(`\\years{${escapeLatex(award.time)}}${escapeLatex(titleWithOptionalDescription)}\\\\`);
    if (award.detail) {
      lines.push(`\\ind ${escapeLatex(award.detail)}  \\\\`);
    }
  });

  lines.push("%------------------------------------------------");
  lines.push("");

  lines.push("\\section*{Publications}");
  if (publications.length === 0) {
    lines.push("\\textit{No publications found in data/publication.}");
  }

  const currentYear = String(new Date().getFullYear());

  publications.forEach((publication) => {
    const yearLabel = publication.forthcoming ? currentYear : publication.publishedAt;
    const escapedTitle = escapeLatex(publication.title);
    const journalLabel = publication.forthcoming
      ? publication.journal
        ? `${publication.journal}, forthcoming`
        : "forthcoming"
      : publication.journal;
    const journalSuffix = journalLabel ? `, \\emph{${escapeLatex(journalLabel)}}` : "";

    if (publication.url) {
      lines.push(`\\years{${escapeLatex(yearLabel)}}\\href{${publication.url}}{\\textbf{${escapedTitle}}}${journalSuffix}\\\\`);
    } else {
      lines.push(`\\years{${escapeLatex(yearLabel)}}\\textbf{${escapedTitle}}${journalSuffix}\\\\`);
    }

    if (publication.authors?.length) {
      lines.push(`${escapeLatex(publication.authors.join(", "))}\\\\`);
    }

    if (publication.awards?.length) {
      publication.awards.forEach((award) => {
        lines.push(`\\ind \\award{${escapeLatex(award)}} \\\\`);
      });
    }

    lines.push("\\medskip");
  });

  lines.push("%------------------------------------------------");
  lines.push("");
  lines.push("\\section*{Media Coverage}");

  const mediaCoverageEntries = publications
    .flatMap((publication) => (
      publication.media_coverage?.map((coverage) => {
        const year = coverage.year
          || extractYearFromUrl(coverage.url)
          || publication.publishedAt
          || "";

        return {
          year,
          outlet: coverage.name,
          label: coverage.label || coverage.name,
          url: coverage.url,
        };
      }) || []
    ));

  mediaCoverageEntries
    .sort((a, b) => {
      const yearDelta = Number(b.year) - Number(a.year);
      if (!Number.isNaN(yearDelta) && yearDelta !== 0) {
        return yearDelta;
      }
      return a.outlet.localeCompare(b.outlet);
    })
    .forEach((entry) => {
      lines.push(`\\years{${escapeLatex(entry.year)}}${escapeLatex(entry.outlet)}: \\href{${entry.url}}{${escapeLatex(entry.label)}}\\\\`);
    });

  return lines;
}

function renderTalkSections(talks) {
  const lines = [];

  const conferenceTalks = talks
    .filter((talk) => !talk.invited)
    .map((talk) => ({ ...talk, parsedDate: parseDate(talk.date) }))
    .sort((a, b) => {
      if (!a.parsedDate || !b.parsedDate) {
        return 0;
      }
      return b.parsedDate.getTime() - a.parsedDate.getTime();
    });

  const talksByTitle = conferenceTalks.reduce((map, talk) => {
    const titleKey = normalizeTitle(talk.title);
    const entries = map.get(titleKey) || [];
    entries.push(talk);
    map.set(titleKey, entries);
    return map;
  }, new Map());

  const sortedTalkGroups = [...talksByTitle.entries()].sort((a, b) => {
    const aDate = a[1][0].parsedDate;
    const bDate = b[1][0].parsedDate;
    if (!aDate || !bDate) {
      return 0;
    }
    return bDate.getTime() - aDate.getTime();
  });

  lines.push("%----------------------------------------------------------------------------------------");
  lines.push("%\tPUBLICATIONS AND TALKS");
  lines.push("%----------------------------------------------------------------------------------------");
  lines.push("");
  lines.push("\\section*{Talks}");
  lines.push("");
  lines.push("\\subsection*{Conferences \\& Workshops}");
  lines.push("");
  lines.push("\\setlength{\\tabcolsep}{0pt}");
  lines.push("\\renewcommand{\\arraystretch}{1.08}");

  sortedTalkGroups.forEach(([title, entries], groupIndex) => {
    lines.push(`\\textbf{${escapeLatex(title)}}\\\\`);
    lines.push("\\begin{tabularx}{\\textwidth}{@{}X@{\\hspace{0.4em}}>{\\raggedleft\\arraybackslash}p{4.8cm}@{}}");

    entries.forEach((talk, index) => {
      const formattedDate = talk.parsedDate ? monthLabel(talk.parsedDate) : talk.date;
      const awardSuffix = talk.award
        ? `\\newline\\hspace*{1em}\\award{${escapeLatex(talk.award)}}`
        : "";
      const rowEnd = index === entries.length - 1 ? "\\\\" : "\\\\[2pt]";
      lines.push(`\\years{${escapeLatex(formattedDate)}}${escapeLatex(talk.conference)}${awardSuffix} & ${escapeLatex(talk.location)} ${rowEnd}`);
    });

    lines.push("\\end{tabularx}");

    if (groupIndex !== sortedTalkGroups.length - 1) {
      lines.push("");
      lines.push("\\medskip");
      lines.push("");
    }
  });

  const invitedTalks = talks
    .filter((talk) => talk.invited)
    .map((talk) => ({ ...talk, parsedDate: parseDate(talk.date) }))
    .sort((a, b) => {
      if (!a.parsedDate || !b.parsedDate) {
        return 0;
      }
      return b.parsedDate.getTime() - a.parsedDate.getTime();
    });

  const invitedByTitle = invitedTalks.reduce((map, talk) => {
    const titleKey = normalizeTitle(talk.title);
    const entries = map.get(titleKey) || [];
    entries.push(talk);
    map.set(titleKey, entries);
    return map;
  }, new Map());

  const invitedTitleGroups = [...invitedByTitle.entries()].sort((a, b) => {
    const aDate = a[1][0].parsedDate;
    const bDate = b[1][0].parsedDate;
    if (!aDate || !bDate) {
      return 0;
    }
    return bDate.getTime() - aDate.getTime();
  });

  lines.push("");
  lines.push("\\subsection*{Invited Talks}");
  lines.push("\\setlength{\\tabcolsep}{0pt}");
  lines.push("\\renewcommand{\\arraystretch}{1.08}");

  invitedTitleGroups.forEach(([title, entries], groupIndex) => {
    lines.push(`\\textbf{${escapeLatex(title)}}\\\\`);
    lines.push("\\begin{tabularx}{\\textwidth}{@{}X@{\\hspace{0.4em}}>{\\raggedleft\\arraybackslash}p{4.8cm}@{}}");

    entries.forEach((talk, index) => {
      const formattedDate = talk.parsedDate ? monthLabel(talk.parsedDate) : talk.date;
      const indicator = talk.discussant ? " (Discussant)" : "";
      const details = `${escapeLatex(talk.conference)}${escapeLatex(indicator)}`;
      const isLastEntry = index === entries.length - 1;
      const rowEnd = isLastEntry ? "\\\\" : "\\\\[2pt]";
      lines.push(`\\years{${escapeLatex(formattedDate)}}${details} & ${escapeLatex(talk.location)} ${rowEnd}`);
    });

    lines.push("\\end{tabularx}");

    if (groupIndex !== invitedTitleGroups.length - 1) {
      lines.push("");
      lines.push("\\medskip");
      lines.push("");
    }
  });

  lines.push("\\renewcommand{\\arraystretch}{1}");

  return lines;
}

function renderSideProjects(profile) {
  const lines = [];

  const entries = [...profile.sideProjects, ...profile.ventures].filter((entry) => entry.includeInCv);

  lines.push("\\section*{Side Projects}");

  entries.forEach((entry) => {
    const label = entry.cvLabel || entry.title;
    const description = entry.cvDescription || entry.description;
    const link = entry.cvLink || entry.link;
    lines.push(`\\years{${escapeLatex(entry.time)}}\\href{${link}}{${escapeLatex(label)}}: ${escapeLatex(description)}\\\\`);
  });

  return lines;
}

async function loadPublications() {
  const publicationDir = path.join(repoRoot, "data", "publication");
  const allFiles = await fs.readdir(publicationDir);
  const mdxFiles = allFiles.filter((file) => file.endsWith(".mdx"));

  const publications = await Promise.all(mdxFiles.map(async (fileName) => {
    const absolutePath = path.join(publicationDir, fileName);
    const fileContents = await fs.readFile(absolutePath, "utf8");
    const { data } = matter(fileContents);

    return {
      title: data.title || "",
      publishedAt: String(data.publishedAt || ""),
      description: data.description || "",
      authors: Array.isArray(data.authors) ? data.authors : [],
      url: data.url || "",
      awards: Array.isArray(data.awards) ? data.awards : [],
      forthcoming: Boolean(data.forthcoming),
      journal: data.journal || "",
      media_coverage: Array.isArray(data.media_coverage) ? data.media_coverage : [],
    };
  }));

  publications.sort((a, b) => {
    const aYear = Number(a.publishedAt) || 0;
    const bYear = Number(b.publishedAt) || 0;
    return bYear - aYear;
  });

  return publications;
}

async function main() {
  await fs.mkdir(generatedDir, { recursive: true });

  const profilePath = path.join(repoRoot, "shared", "profile.json");
  const talksPath = path.join(repoRoot, "shared", "talks.json");

  const profile = JSON.parse(await fs.readFile(profilePath, "utf8"));
  const talks = JSON.parse(await fs.readFile(talksPath, "utf8"));
  const publications = await loadPublications();

  const profileSections = renderProfileSections(profile, publications);
  const talkSections = renderTalkSections(talks);
  const sideProjectSection = renderSideProjects(profile);

  await Promise.all([
    writeTex("profile-sections.tex", profileSections),
    writeTex("talks.tex", talkSections),
    writeTex("side-projects.tex", sideProjectSection),
  ]);

  console.log("Generated CV includes:");
  console.log("- cv/generated/profile-sections.tex");
  console.log("- cv/generated/talks.tex");
  console.log("- cv/generated/side-projects.tex");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
